apiVersion: apps/v1
kind: Deployment
metadata:
  name: newapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: newapp
  template:
    metadata:
      labels:
        app: newapp
    spec:
      containers:
        - name: newapp
          image: salemhammad24/newapp:latest
          ports:
            - containerPort: 8080
