apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-image
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app-image
  template:
    metadata:
      labels:
        app: my-app-image
    spec:
      containers:
      - name: my-app-image
        image: my-app-image/my-app-image:lts
        ports:
        - containerPort: 8080
        - containerPort: 50000
        volumeMounts:
        - name: my-app-image-home
          mountPath: /var/my-app-image-home
      volumes:
      - name: my-app-image-home
        emptyDir: {}

